SELECT SUM(SCORE) AS SCORE, GR.EMP_NO, EM.EMP_NAME, EM.POSITION, EM.EMAIL
FROM HR_EMPLOYEES AS EM
    INNER JOIN HR_GRADE AS GR
    ON EM.EMP_NO = GR.EMP_NO
GROUP BY YEAR, EMP_NO
HAVING GR.YEAR = '2022'
ORDER BY 1 DESC
LIMIT 1;



